# Introduction
Everyone is unique and diverse. Music is a vast and dynamic landscape, and personal preferences and the emotional impact of songs can vary widely from person to person as well. We are in a digital age where streaming services dominate. This allows the availability of extensive music libraries. From these streaming services, APIs open up new avenues for exploring the diverse facets of musical tastes and emotional resonance in numbers. 

As mentioned earlier, there are a multitude of platforms to stream music. Pandora, Apple Music, YouTube, Amazon, and Spotify are popular choices. In most of these platforms, users are not only listeners. They are the curators of their own musical experiences. In order to help each user curate their experience, these platforms read user data and make recommendations and playlists based on their listening preferences. One of the most popular apps is Spotify, and each year, Spotify releases trends for each user based on their listening pattern for the year called “Spotify Wrapped,” which was recently released! For this project, we will use the “spotifyr” package to access extensive data about songs from our top artists of the year. The “spotifyr” package is useful for developers to analyze the the emotions of an artist’s album and look at some insights of the user. However, we will only use the functions to access the artists’ data. 
 
Our decision to explore musical preferences through the Spotify R package is motivated by the desire to understand the intersection of personal taste, emotional connection, and shared musical experiences. By comparing the top tracks between two users, we aim to uncover similarities and differences that may reflect diverse musical journeys and influences. While it is unlikely to have an overlap between our top artists and tracks, it is the moods of the artists that could be insightful. Using the valence, energy, and danceability variables from “spotifyr,” we can compare the moods of artists’ albums.

This exploration not only contributes to our understanding of the intricacies of musical preferences but also sheds light on the emotional narratives woven into music. By combining data-driven insights from the Spotify R package, we aim to offer a comprehensive perspective on the intersection of personal, emotional, and shared experiences within the realm of music. Through this project, we hope to unravel the richness of musical expression and its profound impact on individual and collective identities.
